# Generated by Django 6.0.1 on 2026-02-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[('draft', 'Draft'), ('published', 'Published')], default=0),
        ),
    ]
